name: dr_sohan_raj_tater
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2            # For showing toast messages
  provider: ^6.1.1
  dio: ^5.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  flutter_pdfview: ^1.3.2
  flutter_cached_pdfview: ^0.4.2
  easy_image_viewer: ^1.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
